;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-visual-line
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-semi&comma
        c-electric-slash
        delete-horizontal-space
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        end-of-visual-line
        forward-sexp
        indent-for-tab-command
        kill-region
        kill-visual-line
        mark-sexp
        mark-word
        markdown-outdent-or-delete
        org-self-insert-command
        paredit-delete-char
        paredit-semicolon
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        backward-sentence
        markdown-cycle
        yaml-electric-backspace
        ))
